[gcp_service_account]
type = "service_account"
project_id = "indigo-lotus-458620-p4"
private_key_id = "970c45138d8f404f59f0f4ce519bd99b54809157"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDwtPuQ2iPmhR1t
uUaaSzzdEztFSKwHPhFPVlWpBE+3yU9ksclMdHWcQkS7cAcD1KEgmcbarvHQgATU
rIbPyewoiLRQNrG0Kaxvp2VK0++GTEplftthQGcIbk19n+tmq3mSY1tEuI8BwUch
tJwMpvVXN5LVja0UhXL1pkRheRmbHy2ixZy7rbGOOtUahASmIbAwzrJEd7aLqpg/
mDQVAT20URm8rqE2Tujh4rYAMdME70RghJ1hYMgEg3DlXCnDy7mprHVw1tUJHOjg
nW6Fy5nyGbICSCDYLEJzjW4lw9+g5aM/ARz69zSTvcY4c+Skxazq9sq0q00A5WbF
4DWPDcfBAgMBAAECggEADI60jRMESnNpXJ8M0uHX9ASb0/p9lwci6gur/lxOOF1V
OgCYateshxFh+pFWnFmMamH7YM89qE31co7pnY+ANYEkPwcLcEW4TD7kZun1lgEG
5JKgqUst1N/ERSiBpGKPvhZW3ZfvRf0qU9TTS0muhPVOQLvaaranj68z5A3oSxJU
bLJ1wE645eBTOzHRYbsPI0tZ0lxKXwJ0fKJjot3TparW55tILUC/W6exwDNsb15L
7hWMb4ZFQUhDrkX+/qBssHPYXy00r1DzoKsuAnPfx/kwN5JwO18L2Zc/0tqF4j+P
tS4pPhIImJc2n8Q7o04TJYgBeFjTFsQoPwBn11vNQQKBgQD8PxEHbMs0/gUb7plx
cuSPOnUuxGwya19ULWaupR9OPA444NINd7aaxvWQz6DyHSOA7RdSoPg15r7qzMd5
5JyI7ELccWNwkguh9BXr3q+ZKKgarqz3K893+Bd5YBGI3vvt+m5XwinnRcLfQOjb
DFBDlpLB6AUuteZ37JTj7OlJuQKBgQD0SfTxWQhIjgWR+P9FvNPJ2vvCt4T8DfZl
AnqUZJ3VwBsAbEhqEtX0+RQgB/hiTmVPqiAOZXTd7IkTRXSewOc2ELWI5d/4+rnm
vLK829ShCERG7ZOKRvW+1C5YDLpLnj0fdgBIKYGz1mr5nM3yMa0CoTOqIU+t3Dx6
2r4woX7SSQKBgQC8XK/vtnssMEBKcmsc/6nTltiour79C5cdOeYCpoVxG4GXUbMp
oWq3u7jmkVVjVwULIoEXD+MqBQwuNAsFaATIbn0jNn0GM9kB8E5qW1kPav/VJPk+
ffWoZZfJ6EZPygug0zCQ0goOjNaPdl4sLM7HGeqvZ/5uuiDHDuDEL0ap6QKBgQCJ
xpRQ8ifL092sYESIrmC8Pbc0MJDeH3nRqj48JyslfL091dRZjtoA2eHR1uztdM2K
yqZduDbbWyZMKiYFy0IbqfzYgt147N+gFNixz0HyuFjZr/BAUpkS0VR58GO5djt+
3Ox3xoESTmHy+c7lQ8MR8pzS3Qq1QbsShwAxKUP/kQKBgQCtzdFXFG6NxaUYBeHL
gDXXYsmEW1CgPgba3hXHZOIvIGeBIPDAGLTKPXMAz212VxebbtvZuuvAlFLiikcC
VdDwiPCm42hA42U4csJ8Naa4Sug1skDPcmhqXHeBkHdcYVWIKg0PIWo4IBBWEt3s
zLt8X29Au2cPVN2cpYkrWxBkjw==
-----END PRIVATE KEY-----"""
client_email = "streamlit-service@indigo-lotus-458620-p4.iam.gserviceaccount.com"
client_id = "116623330420772104092"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-service%40indigo-lotus-458620-p4.iam.gserviceaccount.com"
universe_domain = "googleapis.com"